"""Dependency-injection ports consumed by business Services."""

from typing import Protocol

from moex_sentinel.domain.brokers import Broker, BrokerAdapterDefinition, BrokerDraft


class BrokerRepositoryPort(Protocol):
    def list(self) -> list[Broker]: ...

    def get(self, broker_id: str) -> Broker: ...

    def create(self, draft: BrokerDraft) -> Broker: ...

    def replace(self, broker_id: str, draft: BrokerDraft) -> Broker: ...

    def delete(self, broker_id: str) -> bool: ...

    def set_test_account_state(self, broker_id: str, account_id: str, funded: bool) -> Broker: ...


class BrokerRegistryPort(Protocol):
    def list(self) -> tuple[BrokerAdapterDefinition, ...]: ...

    def get(self, adapter_code: str) -> BrokerAdapterDefinition: ...
