<script setup lang="ts">import { ref, watch } from "vue"; import { RouterLink, RouterView, useRouter } from "vue-router"; import HealthStatus from "./components/HealthStatus.vue"; import TradingSessionStatus from "./components/TradingSessionStatus.vue"; import { currentSession, logout, sessionChecked } from "./auth"
import { loadRuntime, runtime } from "./runtime"
watch(currentSession, (session) => { if (session) void loadRuntime(); else runtime.value = null }, { immediate: true })
const router = useRouter()
const logoutError = ref(false)
async function signOut() { logoutError.value = false; try { await logout(); await router.replace({ name: "login" }) } catch { logoutError.value = true } }
const navigation = [{name:"brokers",label:"Брокеры"},{name:"instruments",label:"Инструменты"},{name:"positions",label:"Торговля"},{name:"diagnostics",label:"Диагностика"}]
</script>
<template><main v-if="!sessionChecked || (!currentSession && $route.name !== 'login')" class="auth-loading" aria-label="Проверка сессии" aria-busy="true">Проверка сессии…</main><RouterView v-else-if="!currentSession || $route.name === 'login'" /><div v-else class="app-shell"><aside class="sidebar"><RouterLink class="brand" :to="{ name: 'positions' }"><span class="brand__mark">MS</span><span><strong>MOEX Sentinel</strong><small>{{ runtime?.environment === 'PROD' ? 'ПРОД' : runtime?.environment === 'TEST' ? 'Sandbox' : 'Режим неизвестен' }} · {{ runtime?.access_mode === 'READ_ONLY' ? 'Только чтение' : runtime?.access_mode === 'TRADE' ? 'Торговля' : 'Команды закрыты' }}</small></span></RouterLink><nav aria-label="Основная навигация"><RouterLink v-for="item in navigation" :key="item.name" :to="{ name: item.name }" class="nav-item" exact-active-class="nav-item--active">{{ item.label }}</RouterLink></nav></aside><main><header class="topbar"><div><p class="eyebrow">Локальная платформа</p><h1>MOEX Sentinel</h1></div><div class="topbar__controls"><TradingSessionStatus/><HealthStatus /><button type="button" @click="signOut">Выйти</button><p v-if="logoutError" class="error" role="alert">Не удалось завершить сеанс. Проверьте соединение и повторите попытку.</p></div></header><RouterView /></main></div></template>
